####### MySql Properties ###########
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/jagranplay
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
    
server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: "${spring:application.name}:${random.uuid}"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400
  
jpwallet:
  walletkey: "jpk/dev/jp_wallet_private_key.pem"
  walleturl: "https://stage-connect.jagranplay.com/api/req.php"
  walletredirecturl: "https://stg.jagranplay.com"
  jpredirecturl: "https://stg.jagranplay.com"
  wallettoken: "VV62ecd3432b6ec"
  walletdepositid: "CW-111-16"
  walletwinningid: "CW-111-17"
  walletbonusid: "CW-111-18"
  walletenv: "dev"

resilience4j:
  circuitbreaker:
    instances:
      wallet:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    user:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      wallet:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 10s
      user:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 10s
  ratelimiter:
    instances:
      wallet:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
      user:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s