####### MySql Properties ###########
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/jagranplay
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 
    
server:
  port: 0

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: "${spring:application.name}:${random.uuid}"

management:
  endpoints:
    web:
      exposure:
        include: "*"